package com.akumathreads.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * A promotional discount code that can be applied at checkout.
 *
 * Supports:
 *  - PERCENT codes  (e.g. 10% off subtotal)
 *  - FIXED codes    (e.g. $5 off subtotal)
 *  - Usage limits   (null = unlimited; 1 = single-use welcome/post-purchase)
 *  - Expiry dates   (null = never expires)
 *  - Minimum order  (null = no minimum)
 */
@Entity
@Table(name = "discount_codes")
@Getter @Setter @NoArgsConstructor
public class DiscountCode {

    public enum DiscountType { PERCENT, FIXED }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Unique, uppercase code entered by customer, e.g. "WELCOME10", "OT-X7K2M9" */
    @Column(unique = true, nullable = false, length = 40)
    private String code;

    /** Human-readable label for admin UI */
    @Column(length = 120)
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private DiscountType type = DiscountType.PERCENT;

    /** Percent value (e.g. 10.00 = 10%) or fixed value (e.g. 5.00 = $5 off) */
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal value;

    /** Minimum order subtotal required to use this code. null = no minimum. */
    @Column(precision = 10, scale = 2)
    private BigDecimal minOrderValue;

    /** null = unlimited uses */
    @Column
    private Integer usageLimit;

    @Column(nullable = false)
    private int usedCount = 0;

    /** null = never expires */
    @Column
    private LocalDateTime expiresAt;

    @Column(nullable = false)
    private boolean active = true;

    /** true if this code was auto-generated (welcome / post-purchase) */
    @Column(nullable = false)
    private boolean autoGenerated = false;

    @CreationTimestamp
    @Column(updatable = false)
    private LocalDateTime createdAt;

    public DiscountCode(String code, DiscountType type, BigDecimal value,
                        Integer usageLimit, String description) {
        this.code        = code.toUpperCase().strip();
        this.type        = type;
        this.value       = value;
        this.usageLimit  = usageLimit;
        this.description = description;
    }

    /** True if the code can still be used right now. */
    public boolean isUsable() {
        if (!active) return false;
        if (usageLimit != null && usedCount >= usageLimit) return false;
        if (expiresAt != null && LocalDateTime.now().isAfter(expiresAt)) return false;
        return true;
    }

    /**
     * Calculate discount amount for a given subtotal.
     * Result is capped so it never exceeds the subtotal.
     */
    public BigDecimal calculateDiscount(BigDecimal subtotal) {
        if (type == DiscountType.PERCENT) {
            return subtotal.multiply(value.divide(BigDecimal.valueOf(100)))
                           .setScale(2, java.math.RoundingMode.HALF_UP)
                           .min(subtotal);
        } else {
            return value.setScale(2, java.math.RoundingMode.HALF_UP).min(subtotal);
        }
    }
}
