package com.akumathreads.service;

import com.akumathreads.model.DiscountCode;
import com.akumathreads.repository.DiscountCodeRepository;
import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.List;
import java.util.Optional;

@Service
@RequiredArgsConstructor
@Slf4j
public class DiscountCodeService {

    private static final SecureRandom RNG = new SecureRandom();
    private static final String CHARS = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // no confusable chars

    private final DiscountCodeRepository repo;

    // ── Validation result ─────────────────────────────────────────────────────

    public record ValidationResult(boolean valid, DiscountCode code, String error) {
        public static ValidationResult ok(DiscountCode code)    { return new ValidationResult(true, code, null); }
        public static ValidationResult fail(String error)       { return new ValidationResult(false, null, error); }
    }

    // ── Public API ─────────────────────────────────────────────────────────────

    @Transactional(readOnly = true)
    public ValidationResult validate(String rawCode, BigDecimal subtotal) {
        if (rawCode == null || rawCode.isBlank())
            return ValidationResult.fail("Please enter a discount code.");

        Optional<DiscountCode> opt = repo.findByCodeIgnoreCase(rawCode.strip());
        if (opt.isEmpty())
            return ValidationResult.fail("Code not found.");

        DiscountCode dc = opt.get();
        if (!dc.isUsable())
            return ValidationResult.fail("This code has expired or is no longer valid.");

        if (dc.getMinOrderValue() != null && subtotal.compareTo(dc.getMinOrderValue()) < 0)
            return ValidationResult.fail(
                "Minimum order of $" + dc.getMinOrderValue().toPlainString() + " required.");

        return ValidationResult.ok(dc);
    }

    /** Increment usage count. Call after order is successfully placed. */
    @Transactional
    public void recordUsage(String code) {
        repo.incrementUsedCount(code.toUpperCase().strip());
    }

    @Transactional(readOnly = true)
    public List<DiscountCode> findAll() { return repo.findAllByOrderByCreatedAtDesc(); }

    @Transactional
    public DiscountCode save(DiscountCode dc) { return repo.save(dc); }

    @Transactional
    public void toggleActive(Long id) {
        repo.findById(id).ifPresent(dc -> {
            dc.setActive(!dc.isActive());
            repo.save(dc);
        });
    }

    // ── Code generation ────────────────────────────────────────────────────────

    /**
     * Generate a single-use welcome code, e.g. "WELCOME-X7K2M9".
     * Saved immediately so it is valid for use.
     */
    @Transactional
    public DiscountCode generateWelcomeCode() {
        String code = "WELCOME-" + randomSegment(6);
        DiscountCode dc = new DiscountCode(code,
                DiscountCode.DiscountType.PERCENT,
                BigDecimal.TEN,   // 10%
                1,                // single-use
                "Welcome code — 10% off first order");
        dc.setAutoGenerated(true);
        return repo.save(dc);
    }

    /**
     * Generate a single-use abandoned-cart recovery code, e.g. "BACK-X7K2M9".
     * Saved immediately so it is valid for checkout.
     */
    @Transactional
    public DiscountCode generateRecoveryCode() {
        String code = "BACK-" + randomSegment(6);
        DiscountCode dc = new DiscountCode(code,
                DiscountCode.DiscountType.PERCENT,
                BigDecimal.TEN,   // 10%
                1,                // single-use
                "Abandoned cart recovery — 10% off");
        dc.setAutoGenerated(true);
        return repo.save(dc);
    }

    /**
     * Generate a single-use next-order code, e.g. "NEXT-A4B7C1".
     * Returned to caller to include in post-purchase email.
     */
    @Transactional
    public DiscountCode generateNextOrderCode() {
        String code = "NEXT-" + randomSegment(6);
        DiscountCode dc = new DiscountCode(code,
                DiscountCode.DiscountType.PERCENT,
                BigDecimal.TEN,   // 10%
                1,                // single-use
                "Next-order code — 10% off from post-purchase email");
        dc.setAutoGenerated(true);
        return repo.save(dc);
    }

    // ── Seeding ───────────────────────────────────────────────────────────────

    /** Seed a reusable WELCOME10 promotional code on first startup. */
    @PostConstruct
    @Transactional
    public void seedDefaults() {
        if (repo.findByCodeIgnoreCase("WELCOME10").isEmpty()) {
            DiscountCode dc = new DiscountCode("WELCOME10",
                    DiscountCode.DiscountType.PERCENT,
                    BigDecimal.TEN,
                    null,  // unlimited uses (promotional)
                    "Welcome promo — 10% off (shared code)");
            repo.save(dc);
            log.info("[Discount] Seeded WELCOME10 promo code");
        }
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    private String randomSegment(int length) {
        StringBuilder sb = new StringBuilder(length);
        for (int i = 0; i < length; i++) {
            sb.append(CHARS.charAt(RNG.nextInt(CHARS.length())));
        }
        return sb.toString();
    }
}
